-- Exercise 1
-- Create XXBCM_ORDER_MGT

-- Master table

CREATE TABLE XXBCM_ORDER_MGT (
    ORDER_REF           VARCHAR2(2000),
    ORDER_DATE          VARCHAR2(2000),
    SUPPLIER_NAME       VARCHAR2(2000),
    SUPP_CONTACT_NAME   VARCHAR2(2000),
    SUPP_ADDRESS        VARCHAR2(2000),
    SUPP_CONTACT_NUMBER VARCHAR2(2000),
    SUPP_EMAIL          VARCHAR2(2000),
    ORDER_TOTAL_AMOUNT  VARCHAR2(2000),
    ORDER_DESCRIPTION   VARCHAR2(2000),
    ORDER_STATUS        VARCHAR2(2000),
    ORDER_LINE_AMOUNT   VARCHAR2(2000),
    INVOICE_REFERENCE   VARCHAR2(2000),
    INVOICE_DATE        VARCHAR2(2000),
    INVOICE_STATUS      VARCHAR2(2000),
    INVOICE_HOLD_REASON VARCHAR2(2000),
    INVOICE_AMOUNT      VARCHAR2(2000),
    INVOICE_DESCRIPTION VARCHAR2(2000)
);

SET DEFINE OFF

-- Revised table
CREATE TABLE XXBCM_ORDER_MGT (
    ORDER_REF           VARCHAR2(20) PRIMARY KEY,
    ORDER_DATE          DATE,
    SUPPLIER_NAME       VARCHAR2(100),
    SUPP_CONTACT_NAME   VARCHAR2(100),
    SUPP_ADDRESS        VARCHAR2(255),
    STREET_NO           VARCHAR2(255),
    STREET_NAME         VARCHAR2(100),
    REGION              VARCHAR2(100),
    CITY                VARCHAR2(20),
    COUNTRY             VARCHAR2(100),
    SUPP_CONTACT_NUMBER VARCHAR2(50),
    SUPP_EMAIL          VARCHAR2(100),
    ORDER_TOTAL_AMOUNT  NUMBER(10, 3),
    ORDER_DESCRIPTION   VARCHAR2(255),
    ORDER_STATUS        VARCHAR2(50),
    ORDER_LINE_AMOUNT   NUMBER(10, 3),
    INVOICE_REFERENCE   VARCHAR2(50),
    INVOICE_DATE        DATE,
    INVOICE_STATUS      VARCHAR2(50),
    INVOICE_HOLD_REASON VARCHAR2(255),
    INVOICE_AMOUNT      NUMBER(10, 3),
    INVOICE_DESCRIPTION VARCHAR2(255)
);

SET DEFINE OFF

SELECT
    *
FROM
    XXBCM_ORDER_MGT;


